server.port: 9000

logging:
  level:
    ROOT: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: uaa_app_user
    password: uaa_app_password
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2.console.enable: true
